language: node_js
node_js:
- v9
install:
- npm install
- npm install -g lerna
script:
- lerna bootstrap --ignore-scripts
- lerna run build --scope @devinit/dh-base
- lerna bootstrap
- lerna run build --scope @devinit/dh-app
- lerna run lint
- lerna run test
cache:
  - node_modules
sudo: false
