language: node_js
sudo: false
node_js:
  - v7
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
  - npm install --ignore-scripts
script:
  - npm run lint
  - npm run coverage
  - npm run build
