language: node_js
sudo: false
node_js:
  - v6
  - v7
cache: yarn
install:
  - yarn install --ignore-optional
  - npm install -g codecov
script:
  - npm run lint
  - npm run coverage
  - npm run build
