language: node_js
node_js:
- v9
install:
- npm install --ignore-scripts
script:
- npm run build
- npm run lint
- npm run test
- npm run pull
- npm run build-workers
- npm run build-fragment
- npm run build:next
- mkdir build && mv .next build/ && mv server.js build/ && mv package.json build/ && mv private build/ && mv Dockerfile build/ && mv public build/ && mv nginx build/ && mv docker-compose.yml build/ && mv process.yml build/
- zip -q -r build.zip build
cache:
  - node_modules
sudo: false
