version: '3'
services:
  datahub:
    build: .
    container_name: datahub-new
    ports:
      - "8080:8080"
    command: pm2-docker process.yml
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  nginx:
    build: ./nginx/
    container_name: datahub-nginx
    depends_on:
      - datahub
    ports:
      - "80:80"
    links:
      - datahub:web
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
      replicas: 2
