datahub:
  build: .
  container_name: datahub-new
  ports:
    - "8080:8080"
  command: pm2-docker process.yml

nginx:
  build: ./nginx/
  container_name: datahub-nginx
  ports:
    - "80:80"
  links:
    - datahub:web
